name: Build APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup enviroment
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config libssl-dev
          pip3 install buildozer

      - name: Build APK
        run: buildozer android debug

      - name: Upload‑APK
        uses: actions/upload-artifact@v4
        with:
          name: output-apk
          path: bin/*.apk
